language: elixir
elixir: 1.3.2
services:
  - postgresql
addons:
  postgresql: '9.4'
otp_release:
  - 18.0
sudo: false
before_script:
  - psql -c 'create database todo_test;' -U postgres
  - mix deps.get --only test
script:
  - mix test
