version: '2'
services:
  db:
    image: postgres:9.5
  web:
    build: .
    command: mix phoenix.server
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
